name: ui_pro
description: "A modular, theme-driven Flutter UI system with ready-made widgets and screens. Build consistent, beautiful apps with a single theme configuration."
version: 1.0.0
homepage: https://github.com/harsh308050/ui_pro
repository: https://github.com/harsh308050/ui_pro
issue_tracker: https://github.com/harsh308050/ui_pro/issues

environment:
  sdk: ^3.10.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

license: MIT
